/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Mode = IDL.Variant({
  'scienceHelp' : IDL.Null,
  'socialStudiesHelp' : IDL.Null,
  'languageArtsHelp' : IDL.Null,
  'mathHelp' : IDL.Null,
});
export const ChatRequest = IDL.Record({
  'context' : IDL.Opt(IDL.Text),
  'mode' : Mode,
  'message' : IDL.Text,
});
export const ChatResponse = IDL.Record({
  'mode' : Mode,
  'history' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'response' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'chat' : IDL.Func([ChatRequest], [ChatResponse], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getModePageIntroduction' : IDL.Func([Mode], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Mode = IDL.Variant({
    'scienceHelp' : IDL.Null,
    'socialStudiesHelp' : IDL.Null,
    'languageArtsHelp' : IDL.Null,
    'mathHelp' : IDL.Null,
  });
  const ChatRequest = IDL.Record({
    'context' : IDL.Opt(IDL.Text),
    'mode' : Mode,
    'message' : IDL.Text,
  });
  const ChatResponse = IDL.Record({
    'mode' : Mode,
    'history' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'response' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'chat' : IDL.Func([ChatRequest], [ChatResponse], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getModePageIntroduction' : IDL.Func([Mode], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };